version: '3'

services:
  backend:
    build: .
    volumes:
      - ./cylc:/opt/cylc
    hostname: backend
#    ports:
#      - 3031:3031

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 8080:80

