version: '3'

services:
  cylc:
    build:
      context: ./
      dockerfile: Dockerfile-cylc
    hostname: cylc
    volumes:
      - ./cylc:/opt/cylc
      - ~/.cylc:/home/testuser/.cylc
    container_name: cylc
  pbs:
    build:
      context: ./
      dockerfile: Dockerfile-pbs
      args:
        - CYLC_SSH_PUBKEY=${CYLC_SSH_PUBKEY}
    privileged: true
    hostname: pbs
    volumes:
      - ./cylc:/opt/cylc
      - ~/.cylc:/home/testuser/.cylc
    container_name: pbs
