version: '3'

services:
  cylc:
    build:
      context: ./
      dockerfile: Dockerfile-cylc
    volumes:
      - ./cylc:/opt/cylc
      - cylcrun:/home/testuser/cylc-run
      - ~/.cylc:/home/testuser/.cylc
  pbs:
    build:
      context: ./
      dockerfile: Dockerfile-pbs
      args:
        - CYLC_SSH_PUBKEY=${CYLC_SSH_PUBKEY}
    privileged: true
    hostname: localhost
    volumes:
      - ./cylc:/opt/cylc
      - cylcrun:/home/testuser/cylc-run
      - ~/.cylc:/home/testuser/.cylc

volumes:
  cylcrun:
