version: '3'

services:
  cylc-ssh:
    build: .
    environment:
      - CYLC_SSH_PUBKEY
    volumes:
      - ./cylc:/opt/cylc
      - ~/cylc-run:/root/cylc-run
      - ~/.cylc:/root/.cylc
    ports:
      - 22
    cap_add:
      - NET_ADMIN
  cylc-jump-box:
    build: .
    environment:
      - CYLC_SSH_PUBKEY
    volumes:
      - ./cylc:/opt/cylc
      - ~/cylc-run:/root/cylc-run
      - ~/.cylc:/root/.cylc
    cap_add:
      - NET_ADMIN
